### ISSUE TITLE
Show empire origin

### ISSUE THREAD

**Issue by MichaelMakesGames** [eliasdoehne/stellaris-dashboard#149]
From Stellaris Modding Den Discord:

> Request: for the origin to also be displayed with the other country info (civics, ethics, etc)

### Technical Notes

The origin is not saved currently, so this will requiring edits to `Country` in `datamodel.py` and `CountryProcessor.extract_data_from_gamestate` in `timeline.py`.

For displaying the origin, we need to edit `EventTemplateDictBuilding.country_details` in `history_ledger.py`

**Comment by eliasdoehne** [comment]
No, I never used migrations. Since there is a separate DB created for each game, I did not consider the database to be a long-term storage. I usually just mentioned in the release notes if a change is breaking the schema so people should finish their current game before upgrading. (often this also coincided with a new DLC/game release, which usually breaks save game compatibility anyway)

**Comment by MichaelMakesGames** [comment]
Thoughts on setting up alembic (part of the sqlalchemy project) to automatically migrate the DB?

I suspect schema changes will be needed to support things from the past several Stellaris releases, and it would be nice to be able to release those without breaking things

**Comment by MichaelMakesGames** [comment]
I'll write a separate issue for that
