### ISSUE TITLE
Dashboard does not find any GameSession (might be parsing Issue)

### ISSUE THREAD

**Issue by Kilneana** [eliasdoehne/stellaris-dashboard#60]
Hey there!

Thanks for your work making a Stellaris Dashboard. 

However, I did not get it to work. See my both Videos below where I showcased exactly what I did. 

I think its some kind of parsing issue, it seems the parser exits without doing anything. I was not able to find the error :/ 

https://youtu.be/4TD3x2l-W5M
https://youtu.be/rNWEeQaYJ1Q

**Comment by MichaelMakesGames** [comment]
@Kilneana as far as I can tell from your videos, the dashboard simply did not find any saves to parse. Your save game location is set to `C:\Users\flori\Documents\Paradox Interactive\Stellaris\save games`. I would guess that you have cloud saves enabled, in which case you need to change the location. See https://forum.paradoxplaza.com/forum/threads/how-to-find-the-local-copy-of-your-cloud-save.936661/

Since this is quite old and there's a decent chance you're not even playing Stellaris anymore, I'm going to close this issue. Feel free to reopen

**Comment by Kilneana** [comment]
Hello @MichaelMakesGames,
Thanks for responding to my issue. I am very glad you finally responded :) 

No I am still very active in Stellaris and I am planning on being active for as long as the game remains. 

I am however unable to check today because I am on vacation and I got a new PC. I will try recreating the issue on the weekend and then close the ticket. I hope we can make the dashboard run because I am a huge nerd in terms of numbers and statistics :D 

Many thanks for your response!
