### ISSUE TITLE
Budget graphs look funny when a budget item swaps between positive and negative

### ISSUE THREAD

**Issue by chennin** [eliasdoehne/stellaris-dashboard#83]
Some budget items, for example food from buildings, can be positive or negative. In the code, if the value is ever negative, it's put in a different stackgroup:

https://github.com/eliasdoehne/stellaris-dashboard/blob/9ce3f8ff6183d3785c0952a3b106b84efff3a124/stellarisdashboard/dashboard_app/graph_ledger.py#L475-L477

Problem:

![image](https://user-images.githubusercontent.com/2653277/204382197-607daabe-7a17-4508-9b65-97a2bb669b0a.png)

In the above image, see how the POSITIVE 400 from planet buildings is below the zero line (it's taking -980.65 as its zero at the highlighted time). This fooled me and I looked for buildings that consumed energy, before I saw the lack of a negative sign.

Desired state: negative values are below zero and stack properly and positive values are above zero and stack properly.

This particular save briefly went negative for food from buildings on 2342.07.01. Here is the DB (zipped): 
[exkavaranimus_1358076321.db.zip](https://github.com/eliasdoehne/stellaris-dashboard/files/10107665/exkavaranimus_1358076321.db.zip)

Not how to achieve this? I looked in to it a bit, enough to find the place in code, but didn't see any easy fixes.

**Comment by eliasdoehne** [comment]
I remember I initially assumed that any contribution to the budget would be entirely positive or entirely negative. The reason for separating into two groups is that I wanted everything aligned to the x-axis, with positive contributions above and negatives below (which is the behaviour when the assumption is true). Otherwise we get something like this where positive contributions show up below the axis:

![image](https://user-images.githubusercontent.com/3602589/210753648-adc00bf8-2f68-4422-9cb0-b3d634bc1d4f.png)

It should be solvable by splitting the data into two lists, I just have to try how it will work with the legend label and naming of the series. It's also possible that the dash library has some option for this, I'll check that :shrug:

**Comment by eliasdoehne** [comment]
Ok it was quite easy, fix is here: https://github.com/eliasdoehne/stellaris-dashboard/pull/95/files

![image](https://user-images.githubusercontent.com/3602589/210760322-1e08cbfe-a2e2-4968-b9c1-1073cba035b3.png)

**Comment by eliasdoehne** [comment]
Great I'll merge it!
